#ProsViz file to store constants

#constants
DIR_SAVED_FRAMES = "saved-frames"

#LOOK CONSTANTS
#how much content to fit
NUM_WORDS_TO_SKIP_ON_PAGE_TURN = 20
NUM_SAMPLES_TO_SKIP_ON_PAGE_TURN = 5  #if data is sampled
#sizes
TEXT_SIZE = 20
LEGEND_BOX_SIZE = TEXT_SIZE
LEGEND_HEIGHT = int(TEXT_SIZE * 1.6)
LEGEND_TEXT_SIZE = int(TEXT_SIZE * 0.6)
JUMP_TO_FEATURE_LINE_OFFSET = int(TEXT_SIZE * 2.5)
JUMP_TO_TEXTLINE_OFFSET = int(TEXT_SIZE * 1.5)
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 600
TEXT_SPACE_WIDTH = TEXT_SIZE / 10 
POINT_VALUE_MARKER_SIZE = TEXT_SIZE / 5
PERCENTAGE_VALUE_MARKER_SIZE = TEXT_SIZE / 3
PAUSE_AMPLIFICATION= TEXT_SIZE / 4
WORD_AMPLIFICATION = TEXT_SIZE * 3 #!!!!
EMPTY_SPACE_BTW_TEXT_FEATURES = 3
FONT_TYPE = "Arial"
RIGHT_AXIS_LENGTH=30
LABEL_FEATURE_TEXT_SIZE = TEXT_SIZE / 1.5
PERCENTAGE_FEATURE_MARK_SIZE = TEXT_SIZE / 3

#colors
WORD_BOX_COLOR=[0, 100, 255, 107]
WORD_BOX_LIT_COLOR=[47, 211, 199, 107]  #color if it has a binary-value 1


NO_OF_BINS_IN_CURVE_FEATURES = 10