#constants
DIR_SAVED_FRAMES = "img"

#LOOK CONSTANTS
#window
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700
#how much content to fit
NUM_WORDS_TO_SKIP_ON_PAGE_TURN = 20
NUM_SAMPLES_TO_SKIP_ON_PAGE_TURN = 5  #if data is sampled
#sizes
TEXT_SIZE = 21
MINOR_FIX_SIZE = TEXT_SIZE/7
LEGEND_BOX_SIZE = TEXT_SIZE
LEGEND_HEIGHT = int(TEXT_SIZE * 1.6)
LEGEND_TEXT_SIZE = int(TEXT_SIZE * 0.6)
JUMP_TO_FEATURE_LINE_OFFSET = int(TEXT_SIZE * 2.5)
JUMP_TO_TEXTLINE_OFFSET = int(TEXT_SIZE * 1.5)
TEXT_SPACE_WIDTH = TEXT_SIZE / 10 
POINT_VALUE_MARKER_SIZE = TEXT_SIZE / 5
PERCENTAGE_VALUE_MARKER_SIZE = TEXT_SIZE / 3
PAUSE_AMPLIFICATION = TEXT_SIZE * 1.5 
WORD_AMPLIFICATION = TEXT_SIZE * 3 #!!!!
EMPTY_SPACE_BTW_TEXT_FEATURES = 3
FONT_TYPE = "Arial"
RIGHT_AXIS_LENGTH=30
LABEL_FEATURE_TEXT_SIZE = TEXT_SIZE / 2
PERCENTAGE_FEATURE_MARK_SIZE = TEXT_SIZE / 3

#colors
WORD_BOX_COLOR=[237, 104, 60, 90]
PUNC_BOX_COLOR=[233, 104, 58, 230]
PAUSE_BOX_COLOR=[252, 231, 72, 107]
PUNC_PAUSE_BOX_COLOR=[252, 231, 72, 107]

WORD_BOX_LIT_COLOR=[47, 211, 199, 200]  #color if it has a binary-value 1

NO_OF_BINS_IN_CURVE_FEATURES = 100

MAX_HZ = 300
MAX_SEMITONE = 10
